### ISSUE TITLE
关于huanhuan-chat微调报错的问题

### ISSUE THREAD

**Issue by JiQiangHuang** [KMnO4-zx/huanhuan-chat#14]
因为刚入门大模型有很多东西不是很懂，我想咨询一下关于微调时候报错NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.的问题。您有时间解答一下吗？谢谢！

训练参数没有改，错误如下：
从../dataset/train/lora/huanhuan.json加载数据集失败

NotImplementedError( "Loading a dataset cached in a LocalFileSystem is not supported. ")

**Comment by KMnO4-zx** [comment]
您好，有一个可能的原石是这样的：由于训练脚本是放在`fine_tune/lora`目录下的，所以数据集的正确加载路径应该是`../../dataset/train/lora/huanhuan.json`。

**Comment by shiv-cd** [comment]
@JiQiangHuang 检查一下 `fsspec` 是否安装正确，`is_remote_filesystem` 依赖它判断的。

**Comment by anine09** [comment]
实际上该问题来自 https://github.com/huggingface/datasets/issues/6352，该问题由 `fsspec` 的破坏性更新引起，已在 `datasets 2.14.6` 中修复，而本项目 [`requirements.txt`](https://github.com/KMnO4-zx/huanhuan-chat/blob/master/requirements.txt?plain=1#L24) 中为
```
datasets==2.12.0
```

@KMnO4-zx 建议重新检查依赖关系，并更新 requirements.txt
