### ISSUE TITLE
Error Report:  pip install no such file or directory

### ISSUE THREAD

**Issue by hsiong** [KMnO4-zx/huanhuan-chat#15]
pip install -r requirements.txt 报错  `no such file or directory`
 
requirements.txt 内引入了很多静态路径, 部分如下: 想问下是在虚拟机还是云台内运行? 还是 ? 

<img width="661" alt="Screenshot 2023-10-24 at 18 05 02" src="https://github.com/KMnO4-zx/huanhuan-chat/assets/37357447/cb3bce3d-e001-4ecc-bdc6-dd0ba7d5f830">

**Comment by KMnO4-zx** [comment]
您好，我想问一下您是不是没有切换到项目目录呀？

**Comment by logan-zou** [comment]
已更新依赖文件，请重试

**Comment by hsiong** [comment]
> 已更新依赖文件，请重试

可以了   十分感谢!
