### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by Chenwe111** [KMnO4-zx/huanhuan-chat#18]
hi，很棒的开源项目，我最近对此也比较感兴趣，有几个问题想请教一下：
1. 我看训练数据中对于“你是谁”和“你是”两个问题进行了重采样，是强行让模型学到这部分知识吗？我在想可以通过提示词的方式去控制人设吗？
2. 微调后人物语气生成的场景受问题影响大吗，比如某些问题生成会差一些之类的吗？
3. sft之后会有灾难性遗忘吗？

**Comment by logan-zou** [comment]
您好，非常感谢您的关注：
1. 重采样的目的确实是加强知识注入以强化模型在自我认知类问题的表现；提示词来控制人设是可以的，但是由于6B、13B量级模型能力有限，对于复杂提示词难以理解；同时，由于我们使用简单指令微调，其复杂指令理解能力受到了一定破坏。我们正在探究复杂指令微调的思路来同时保证个性化风格与指令理解能力，敬请期待；
2. 会有质量波动，根据问题会产生风格质量波动，且暂时没有表现出来具体规律，推测与数据集组成有关；
3. 会有的，且与微调方式密切相关；如果要避免灾难性遗忘，需要采取新数据与旧数据按比例混合的形式进行微调；但由于我们的目的是打造个性化的聊天机器人，因此我们并不强求其对原本世界知识仍然具有较好的记忆效果。

**Comment by Chenwe111** [comment]
> 您好，非常感谢您的关注：
> 
> 1. 重采样的目的确实是加强知识注入以强化模型在自我认知类问题的表现；提示词来控制人设是可以的，但是由于6B、13B量级模型能力有限，对于复杂提示词难以理解；同时，由于我们使用简单指令微调，其复杂指令理解能力受到了一定破坏。我们正在探究复杂指令微调的思路来同时保证个性化风格与指令理解能力，敬请期待；
> 2. 会有质量波动，根据问题会产生风格质量波动，且暂时没有表现出来具体规律，推测与数据集组成有关；
> 3. 会有的，且与微调方式密切相关；如果要避免灾难性遗忘，需要采取新数据与旧数据按比例混合的形式进行微调；但由于我们的目的是打造个性化的聊天机器人，因此我们并不强求其对原本世界知识仍然具有较好的记忆效果。

感谢您的分享，回答对我帮助很大，已经star，会持续关注项目一起学习。
另外还有一个问题，希望可以给我一些建议。
我现在想微调一个文本转述的模型，类似给定一个官方文本，然后转写出带有角色口吻和语气的话。指令微调能做吗？希望可以给我一些建议，感谢！

**Comment by logan-zou** [comment]
如果是针对单一语气的文本转述模型，简单的指令微调就可以起到较好的效果，可以参考嬛嬛的微调方式；如果是想要做到针对多种语气的转述的话，就需要复杂指令微调的方法了，但总体来说指令微调是可以实现您的目标的。

**Comment by Chenwe111** [comment]
> 如果是针对单一语气的文本转述模型，简单的指令微调就可以起到较好的效果，可以参考嬛嬛的微调方式；如果是想要做到针对多种语气的转述的话，就需要复杂指令微调的方法了，但总体来说指令微调是可以实现您的目标的。
感谢您的指点！祝好

**Comment by Chenwe111** [comment]
> 如果是针对单一语气的文本转述模型，简单的指令微调就可以起到较好的效果，可以参考嬛嬛的微调方式；如果是想要做到针对多种语气的转述的话，就需要复杂指令微调的方法了，但总体来说指令微调是可以实现您的目标的。

感谢指点，祝好！
