### ISSUE TITLE
没有GPT的情况下怎样复现嬛嬛

### ISSUE THREAD

**Issue by oreo-yum** [KMnO4-zx/huanhuan-chat#19]

**Comment by KMnO4-zx** [comment]
你可以用我们已有的数据集呀~

**Comment by oreo-yum** [comment]
谢谢，已经训练成功，这个数据可以直接用 text-generation-webui 进行训练

**Comment by ycjcl868** [comment]
> 你可以用我们已有的数据集呀~

已有数据集也需要 OpenAILLM 做切分吧，没看到训练数据集
