### ISSUE TITLE
pip安装依赖时报安装包冲突。

### ISSUE THREAD

**Issue by zhanghui-china** [KMnO4-zx/huanhuan-chat#20]
pip安装依赖时，报：
![image](https://github.com/KMnO4-zx/huanhuan-chat/assets/63148804/82dbad09-1316-40f6-ae62-8dc74e7bf3c1)

**Comment by zhanghui-china** [comment]
已通过分批安装的方式解决。

**Comment by navono** [comment]
> 已通过分批安装的方式解决。

我也遇到了安装依赖包错误。你是怎么个分批法？
