### ISSUE TITLE
数据集inputs和labels重合的问题

### ISSUE THREAD

**Issue by YuGuilliman** [KMnO4-zx/huanhuan-chat#31]
我发现做SFT中的inputs和labels出现了重合，请问这是合适的吗？本人现在还是在入门LLM的小白，不大懂这方面
![9aeb84528d5f5cb5f975a9e04ec3af2](https://github.com/user-attachments/assets/ceed7ee9-2660-44fe-a870-7650b68f41c5)

**Comment by KMnO4-zx** [comment]
正常的，input_ids是包含label的，只不过在训练过程中只计算label的loss

**Comment by YuGuilliman** [comment]
啊，谢谢你的回答
