### ISSUE TITLE
Why is the input text written in "Instruction" instead of "input"?

### ISSUE THREAD

**Issue by Alsacen** [KMnO4-zx/huanhuan-chat#4]

**Comment by nowadays0421** [comment]
For large language models trained with instructions, "instruction" and "input" refer to different concepts.

"Instruction" refers to the directive or action you want the model to perform, such as completing a piece of text.

"Input", on the other hand, refers to the information the model needs to fulfill your instruction. For instance, when you ask the model to complete a piece of text, you should provide the text that needs to be completed as the input.

In our project, we require the model to respond to the user's query similar to how Zhen Huan responds. This means we simplify the instruction to a question-and-answer format, and as a result, the user's question becomes the aforementioned "instruction," and there is no need for additional "input."

**Comment by EasonQYS** [comment]
请问这两种方式，训练表现的差异是什么？我想要做对话风格迁移（连续对话），选哪种比较好呢？谢谢！
